### ISSUE TITLE
Error in preprocessNoob(RGset, verbose=10) - script killed

### ISSUE THREAD

**Issue by Fjeanneret** [hansenlab/minfi#229]
Hi there,

I need help understanding an unknown behavior of my methylation-array preprocessing script.

I have successfully used this function for 27k array of an experiment. However, for the 450k samples I got a "killed" jupyter session or script used with Rscript that were running this function.
Is it only an issue of memory and something related to my computer perfomances?

```R
preprocessNoob(RGset, verbose=10)
```

The _verbose=10_ returned:
`[normexp.get.xs] Background mean & SD estimated from 178374 probes`
`[normexp.get.xs] Background mean & SD estimated from 92578 probes`

Thanks for your time,
Cheers,

Florian Jeanneret

**Comment by wvictor14** [comment]
Hi Florian, how many samples are you running and what is your RAM capacity?

It usually does not require that much memory, I can process ~100 samples on my 16 gb laptop no problem.

You can monitor your ram usage while it is running, to see if the session dies as RAM usage approaches the limit.

**Comment by Fjeanneret** [comment]
Hi Victor, 

Actually, I was running 472 samples from the KIRC TCGA data with a 32GiB RAM capacity.
An other try gave me the following output before be killed:
`[normexp.get.xs] Background mean & SD estimated from 178374 probes
[normexp.get.xs] Background mean & SD estimated from 92578 probes
[dyeCorrection] Applying R/G ratio flip to fix dye bias` 

Apparently, the memory usage was about 22GiB and was greatly increasing before be killed. I guess the issue here is the number of samples (or my RAM capacity).

Any thoughts about preprocessing of large amount of data (or specifically TCGA data) with the noob method?

Thanks a lot for you quick answer,
Cheers,
Florian

**Comment by wvictor14** [comment]
Hi Florian, ah it sounds like a ram issue.

One option is to normalize in subsets. Because preprocessNoob by default processes samples 1 at a time, you can do this and then combine the normalized data afterwards. Just make sure to start a new R session / clear your environment before normalizing each subset so as to maximize RAM availability.

"How should dye bias correction be done: use a single sample approach (ssNoob), or a reference array?" - [preprocessNoob](https://rdrr.io/bioc/minfi/man/preprocessNoob.html). Can read about it in the 2017 publication.

**Comment by Fjeanneret** [comment]
Hi Victor,

This is perfect. 
Thank you!

Have a nice day,
Florian
